=== ntduyit2023/xml/18 - 19/DTD/breakfast-menu.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/breakfast-menu.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE breakfast-menu SYSTEM "breakfast-menu.dtd">

    <breakfast-menu>
    ...
    </breakfast-menu>
-->

<!ELEMENT breakfast-menu (food+)>
<!ELEMENT food (name, price, description, calories)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT calories (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/breakfast-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE breakfast-menu SYSTEM "../DTD/breakfast-menu.dtd" >
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<breakfast-menu>
    <food>
        <name>Pho bo</name>
        <price>35.000 VND</price>
        <description>Pho bo Ha Noi nuoc dung dam da, banh pho mem</description>
        <calories>450</calories>
    </food>
    <food>
        <name>Banh mi trung </name>
        <price>20.000 VND</price>
        <description>Banh mi gion voi trung op la, cha lua va do chua</description>
        <calories>350</calories>
    </food>
    <food>
        <name>Xoi xeo </name>
        <price>25.000 VND</price>
        <description>Xoi nep thom voi hanh phi, ruoc va da heo</description>
        <calories>400</calories>
    </food>
    <food>
        <name>Banh cuon (Steamed rice rolls)</name>
        <price>30.000 VND</price>
        <description>Banh banh cuon mem voi nhan thit va nam</description>
        <calories>300</calories>
    </food>
</breakfast-menu>
