=== ntduyit2023/xml/18 - 19/DTD/danhsachnv.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/danhsachnv.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE danhsach SYSTEM "danhsachnv.dtd">

    <danhsach>
    ...
    </danhsach>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT danhsach (nhanvien)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nhanvien (ma,ho,ten,anh)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ma (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ho (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ten (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT anh (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/danhsachnv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE danhsach SYSTEM "../DTD/danhsachnv.dtd" >

<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<danhsach>
    <nhanvien>
        <ma>1</ma>
        <ho>Nguyễn</ho>
        <ten>Sơn</ten>
        <anh>https://domain.com.vn/img/son.jpg</anh>
    </nhanvien>
    <nhanvien>
        <ma>2</ma>
        <ho>Phạm</ho>
        <ten>An</ten>
        <anh>https://domain.com.vn/img/an.jpg</anh>
    </nhanvien>
    <nhanvien>
        <ma>3</ma>
        <ho>Trần</ho>
        <ten>Phước</ten>
        <anh>https://domain.com.vn/img/phuoc.jpg</anh>
    </nhanvien>
</danhsach>
