=== ntduyit2023/xml/18 - 19/DTD/ds_sinhvien.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/list_student.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE daihoc SYSTEM "list_student.dtd">

    <daihoc>
    ...
    </daihoc>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT daihoc (khoa)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT khoa (lop)*>
<!ATTLIST khoa
    ma_khoa ID #REQUIRED
    ten_khoa CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lop (sinhvien)*>
<!ATTLIST lop
    ma_lop ID #REQUIRED
    ten_lop CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sinhvien (ho_ten,email,dia_chi,sdt)>
<!ATTLIST sinhvien
    mssv ID #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ho_ten (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dia_chi (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sdt (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/ds_sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE daihoc SYSTEM "../DTD/ds_sinhvien.dtd" >
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<daihoc>
    <khoa ma_khoa="CNTT" ten_khoa="Công nghệ thông tin">
        <lop ma_lop="CNTT01" ten_lop="Lớp Công nghệ thông tin 1">
            <sinhvien mssv="SV001">
                <ho_ten>Nguyễn Văn A</ho_ten>
                <email>nva@example.com</email>
                <dia_chi>256 Đường Nguyễn Văn Cừ, P.Cái Khế, TP.Cần Thơ</dia_chi>
                <sdt>0901234567</sdt>
            </sinhvien>
            <sinhvien mssv="SV002">
                <ho_ten>Trần Thị B</ho_ten>
                <email>ttb@example.com</email>
                <dia_chi>258 Đường Nguyễn Văn Cừ, P.Cái Khế, TP.Cần Thơ</dia_chi>
                <sdt>0912345678</sdt>
            </sinhvien>
        </lop>
    </khoa>
    
    <khoa ma_khoa="KT" ten_khoa="Kinh tế">
        <lop ma_lop="KT01" ten_lop="Lớp Kế toán 1">
            <sinhvien mssv="SV003">
                <ho_ten>Lê Văn C</ho_ten>
                <email>lvc@example.com</email>
                <dia_chi>254 Đường Nguyễn Văn Cừ, P.Cái Khế, TP.Cần Thơ</dia_chi>
                <sdt>0987654321</sdt>
            </sinhvien>
        </lop>
    </khoa>
</daihoc>
