=== ntduyit2023/xml/18 - 19/DTD/list.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/list.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE list SYSTEM "list.dtd">

    <list>
    ...
    </list>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT list (student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (name,genre,CPA,email,address)>
<!ATTLIST student
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT genre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CPA (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT address (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../DTD/list.dtd" >

<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<list>
<student id="01">
<name>Peabo Bryson</name>
<genre>Male</genre>
<CPA>2.81</CPA>
<email>pb@mail.com</email>
<address>Hawaii, USA</address>
</student>
<student id="02">
<name>Celine Dion</name>
<genre>Female</genre>
<CPA>3.38</CPA>
<email>cd@mail.com</email>
<address>Ottawa, Canada</address>
</student>
</list>
