=== ntduyit2023/xml/18 - 19/DTD/list_student.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/list_student.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE list SYSTEM "list_student.dtd">

    <list>
    ...
    </list>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT list (class,students)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT class (#PCDATA)>
<!ATTLIST class
    id ID #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT students (student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (number,lastname,firstname,grade)>
<!ATTLIST student
    idClass IDREF #REQUIRED
    gender (0|1) #REQUIRED
    top CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT number (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lastname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT firstname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT grade (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/list_student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../DTD/list_student.dtd" >

<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<list>
    <class id="C001">Lớp Công nghệ thông tin K11</class>
    <class id="C002">Lớp Khoa học dữ liệu K11</class>
    <students>
        <student idClass="C001" gender="1">
            <number>001</number>
            <lastname>Nguyễn</lastname>
            <firstname>Văn An</firstname>
            <grade>8.5</grade>
        </student>
        
        <student idClass="C001" gender="0" top="yes">
            <number>002</number>
            <lastname>Trần</lastname>
            <firstname>Thị Ba</firstname>
            <grade>9.2</grade>
        </student>
        
        <student idClass="C002" gender="1" top="yes">
            <number>003</number>
            <lastname>Lê</lastname>
            <firstname>Văn C</firstname>
            <grade>9.5</grade>
        </student>
        
        <student idClass="C002" gender="0">
            <number>004</number>
            <lastname>Phạm</lastname>
            <firstname>Thị D</firstname>
            <grade>8.0</grade>
        </student>
    </students>
</list>
