=== ntduyit2023/xml/18 - 19/DTD/monan.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/monan.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE danhsachmonan SYSTEM "monan.dtd">

    <danhsachmonan>
    ...
    </danhsachmonan>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT danhsachmonan (mon)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT mon (ten,gia,mota,nangluong,lienket)>
<!ATTLIST mon
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ten (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT gia (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT mota (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nangluong (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lienket (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/monan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE danhsachmonan SYSTEM "../DTD/monan.dtd" >
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<danhsachmonan>
<mon id="1">
<ten>Phở Bò</ten>
<gia>50000</gia>
<mota>Mon pho truyền thống với nuớc dung dam da va thit bò tuoi</mota>
<nangluong><![CDATA[450 kcal (ước tính, phục vụ 1 tô)]]></nangluong>
<lienket><![CDATA[<a href="https://example.com/pho-bo">Chi tiết món Phở
Bò</a>]]></lienket>
</mon>
<mon id="2">
<ten>Banh Mì Thịt</ten>
<gia>25000</gia>
<mota>Bánh mì giòn kẹp thịt nguội và rau tươi</mota>
<nangluong><![CDATA[300 kcal (chi mang tinh tham khao)]]></nangluong>
<lienket><![CDATA[<a href="https://example.com/banh-mi-thit">Chi tiet Banh Mi
Thit</a>]]></lienket>
</mon>
</danhsachmonan>
