=== ntduyit2023/xml/18 - 19/DTD/part.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/part.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE parts SYSTEM "part.dtd">

    <parts>
    ...
    </parts>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT parts (title,part+)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT part (item,manufacturer,model,cost)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT manufacturer (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT model (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cost (#PCDATA)>

=== ntduyit2023/xml/18 - 19/XML/part.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parts SYSTEM "../DTD/part.dtd" >

<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<parts>
    <title>computer parts</title>
    <part>
        <item id="01">motherboard</item>
        <manufacturer>asus</manufacturer>
        <model>p3b-f</model>
        <cost>123.00</cost>
    </part>
    <part>
        <item id="02">video card</item>
        <manufacturer>ati</manufacturer>
        <model>all-in-wonder pro</model>
        <cost>160.00</cost>
    </part>
    <part>
        <item id="03">sound card</item>
        <manufacturer>creative labs</manufacturer>
        <model>sound blaster live</model>
        <cost>80.00</cost>
    </part>
</parts>
